### ISSUE TITLE
How to use iperf to measure the network parameters of a container（virtual firewall） between two containers？

### ISSUE THREAD

**Issue by GuoJuny** [nerdalert/iperf3#15]
Hello, I am sorry to disturb you.
I would like to ask how to use iperf to measure the network parameters of the container between the iperf-client and iperf-server container. I would like to measure the network parameters of an intermediate container (e.g. vFW), but every time I generate traffic using iperf-client, the traffic is transferred directly from the iperf-client container to the iperf-server container and does not pass through the intermediate container. How can I solve this problem please?

**Comment by nerdalert** [comment]
Hello! Sounds like you need to add some magic to get the traffic routing between the two containers to funnel through the firewall. From your description, it sounds like no traffic is traversing the firewall, not just iperf traffic.

**Comment by chahongwu** [comment]
I don't know if you're talking about penetrating the firewall. If so, it seems like you can use the - R parameter
