### ISSUE TITLE
Bandwidth Limits

### ISSUE THREAD

**Issue by Veldkornet** [nerdalert/iperf3#3]
I'm currently running this docker on my Synology NAS which has a 4Gbit LACP connection to the switch.
Connected to the same switch is my pc via a 2Gbit LACP connection.

However, when I run the iperf docker in server mode, I can't get above 900Mb from PC to NAS.
Where I'd expect to at least get 2Gbit....

What am I missing?

```
c:\iperf-3.1.3-win64>iperf3.exe -c 192.168.1.2 
Connecting to host 192.168.1.2 , port 5201
[  4] local 192.168.1.28 port 20741 connected to 192.168.1.2 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   109 MBytes   915 Mbits/sec
[  4]   1.00-2.00   sec   110 MBytes   920 Mbits/sec
[  4]   2.00-3.00   sec   112 MBytes   941 Mbits/sec
[  4]   3.00-4.00   sec   109 MBytes   913 Mbits/sec
[  4]   4.00-5.00   sec   110 MBytes   927 Mbits/sec
[  4]   5.00-6.00   sec   109 MBytes   915 Mbits/sec
[  4]   6.00-7.00   sec   111 MBytes   933 Mbits/sec
[  4]   7.00-8.00   sec   108 MBytes   906 Mbits/sec
[  4]   8.00-9.00   sec   109 MBytes   917 Mbits/sec
[  4]   9.00-10.00  sec   111 MBytes   929 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  1.07 GBytes   921 Mbits/sec                  sender
[  4]   0.00-10.00  sec  1.07 GBytes   921 Mbits/sec                  receiver
```

**Comment by nerdalert** [comment]
Hiya, can you get stats from the switch ports themselves? It kinda sounds like one is blocking which could be due to a misconfiguration on the LAG group. You could also check the NICs and ensure they are both tx/rx. Just a guess but thats where I would probably start.
Cheers!

**Comment by Veldkornet** [comment]
Okay thanks. I just wanted to check that there was not some unknown limit that I should be aware of related to docker and the way it does it's networks etc. In that case, I'll start looking into the switch, thanks! :)
