### ISSUE TITLE
Update dockerhub image with the latest iperf3 version

### ISSUE THREAD

**Issue by CosminNechifor** [nerdalert/iperf3#7]
# Feature request:

Hello @nerdalert and @isaiahtaylor ,

After using ``networkstatic/iperf3`` image from docker hub, I've seen that it uses version 3.0.7, meanwhile version 3.6 is available. Will you guys build and publish the new version?

```
/# iperf3 --version
iperf 3.0.7
```
Latest version (after building using this repo's Dockerfile):
```
docker run -it --rm -p 5201:5201 cosminpetru/iperf3 --version
iperf 3.6 (cJSON 1.5.2)
```

**Comment by nerdalert** [comment]
@CosminNechifor done friend. Ty for the feedback!

```
(='o'=) [iperf3]$ docker run -it --rm networkstatic/iperf3 --version
iperf 3.6 (cJSON 1.5.2)
Linux fedaf3d4d204 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication
```
